Add bookings
PorotikovSergey/java-shareit pull request #3
Opened 2022-09-02 19:56 UTC by PorotikovSergey

2022-09-03 08:23 UTC, PorotikovSergey commented
Я не очень понял на сколько сильно мы должны запросными методами из JpaRepository пользоваться. Есть ощущение что иногда понятнее сначала обычный findAll(), а потом уже в бизнес логике через streamApi вытащить нужное по дополнительным параметрам. А с другой стороны вообще всю логику можно запихнуть в запросные методы, но они тогда получаются монструозными и пугающе длинными... Короче, я как-то "по наитию" использовал и первый и второй вариант, но если надо после ревью могу сместить свой код в любую из сторон

2022-09-04 12:53 UTC, makholin commented on default.trace.db
> +2022-09-03 08:02:40 jdbc[3]: exception
кажется, что этот файл с логами можно исключить из гита

2022-09-04 12:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "booker_Id")
названия колонок должно быть без заглавных букв

2022-09-04 12:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "item_Owner_Id")
лучше назвать колонку просто `owner_id`

2022-09-04 12:57 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String SHARER_ID_HEADER = "X-Sharer-User-Id";
лучше назвать `USER_ID_HEADER`

 нужно константы от других полей отделить пустой строкой

2022-09-04 12:57 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingMapper bookingMapper;
нужно добавить private final

2022-09-04 12:59 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingDto.java
> +    private long itemOwnerId;
поле тоже можно назвать ownerId, по контексту приложения будет понятно, что за владелец имеется ввиду

2022-09-04 13:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Collection<Booking> getAllForCurrentUser(String state, String curUser);
Current тут непонятно, что означает
можно просто `getAllForUser(state, user)`

2022-09-04 13:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    BookingRepository bookingRepository;
private final

2022-09-04 13:03 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    Set<Booking> result = new TreeSet<>((o1, o2) -> (o2.getStart().compareTo(o1.getStart())));
сервис должен быть stateless: у него не должно быть состояния

сейчас же работа его методов зависит от того, что хранится в этом сете

2022-09-04 13:05 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    Set<Booking> result = new TreeSet<>((o1, o2) -> (o2.getStart().compareTo(o1.getStart())));
если нужно сет с заданной сортировкой, то нужно сделать его локальной переменной в методе

2022-09-04 13:06 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public Booking patchBooking(String bookingId, String sharerId, String approved) {
лучше в маппере отдельно смапить queryParam в boolean, и в сервис уже передавать булеан значение

2022-09-04 13:10 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus() != BookingStatus.APPROVED) {
нужно упростить, такие if else сложно читать и в них легко сделать ошибку

```
if (booking.getStatus() == BookingStatus.APPROVED) {
    throw new ValidationException("Нельзя менять статус уже подтверждённой брони");
}

booking.setStatus(approved ? BookingStatus.APPROVED : BookingStatus.REJECTED)
            
return strongBookingMaker(booking);
```

2022-09-04 13:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        long idOfBooking = Long.parseLong(bookingId);
лучше 
```
parsedBookingId
parsedOwnerId
```

2022-09-04 13:14 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Booking booking = bookingRepository.getReferenceById(idOfBooking);
странное название у метода репозитория, лучше стандартное для репозиториев `findById` или `findByBookingId`

2022-09-04 13:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else {
тоже стоит избавиться от if else

лучше 
```
if (...) {
    throw new Exception();
 }
return strongBookingMaker(booking);
```

2022-09-04 13:20 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } catch (Exception e) {
не стоит такой большой кусок логики оборачивать в try и ловить вообще все исключения
там может случиться что угодно и любая ошибка будет смаплена в ValidationException

вообще, статус должен быть отвалидирован до выполнения каких-либо операций и на моменте валидации должен выброситься эксепшен

если выполнение пошло дальше по методу, то предполагается, что данные все правильные

2022-09-04 13:22 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +//----------------------------всякая вспомогательная фигня--------------------------------------------------------------
не стоит добавлять такие комментарии, они никому не помогут лучше понять код
если методов много и в них тяжело ориентироваться, то лучше разнести их по нескольким классам

2022-09-04 13:23 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private Item getItemForBooking(Item item) {
зачем нужна копия итема с теми же самыми данными?

2022-09-04 13:26 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    @Column(name = "item_Id")
item_id

2022-09-04 13:28 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "owner_Id")
owner_id

2022-09-04 13:30 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } catch (NumberFormatException e) {
id нужно отвалидировать заранее

2022-09-04 13:31 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NotFoundException("Бронирования на данный айтем не было");
везде к сообщениям ошибок стоит добавлять id сущностей, с которыми они связаны, чтобы потом легче было понимать в чем проблема

2022-09-04 13:43 UTC, makholin commented on src/main/java/ru/practicum/shareit/requests/ItemRequestDto.java
> +public class ItemRequestDto {
нужно добавить поля?

2022-09-04 13:44 UTC, makholin commented on src/main/resources/schema.sql
> +                                     requestorId BIGINT NOT NULL,
названия колонок должны быть все в одном стиле
лучше маленькими буквами и с разделением слов через нижнее подчеркивание

2022-09-04 13:50 UTC, makholin requested changes
Нужно исправить замечания

Обычно фильтрацию нужных данных и сортировку делают на стороне бд, потому что внутреннее устройство баз данных делает это гораздо оптимальнее и быстрее. Плюс не нужно гонять большие массивы данных по сети, а сделать выборку в бд и вернуть только то, что действительно нужно

Но все эти улучшения заметны только на большом объеме данных
Например, в реальном проекте в каждой таблице может быть больше миллиона записей, если их все передавать в спринговый сервис - он просто упадет

А где фильтровать и сортировать несколько записей из бд в учебном проекте - не так важно с точки зрения оптимизаций

2022-09-04 20:03 UTC, PorotikovSergey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Booking booking = bookingRepository.getReferenceById(idOfBooking);
так я ж тут стандартный метод из jpa использую - его так до меня уже назвали.

2022-09-04 20:43 UTC, PorotikovSergey commented on src/main/java/ru/practicum/shareit/booking/BookingDto.java
> +    private long itemOwnerId;
хм, любое переименование этой переменной ломает весь проект и он просто не запускается... интересно, надо бы разобраться

2022-09-05 19:30 UTC, PorotikovSergey commented on src/main/java/ru/practicum/shareit/booking/BookingDto.java
> +    private long itemOwnerId;
Просто есть ощущение, что это название явно указывает, что это владелец вещи, а не бронирования, запроса или ещё чего. Если не совсем критично, то я бы хотел оставить такое название. А если критично, то в следующем ревью поменяю

2022-09-05 19:54 UTC, PorotikovSergey commented
Я, вроде всё исправил, только 2 момента оставил. 
1)переменную itemOwnerId я не стал переименовывать в ownerId. С одной стороны вроде и вправду излишне, а с другой есть ощущение, что "айди владельца" не совсем точно определяет владелец чего- может это человек на кого оформлено бронирование, или человек оставивший на него запрос... А так сразу становится понятно, что это владелец арендованной вещи. 
2)название метода getReferenceById() - это ж из стандартных запросов к JpaRepository. Это не я придумал
=====
А, ну и в букинге, который возвращается на запрос внутренние поля(те что Item и Booker) я сделал что б они были не своими обычными классами, а Dto. Логика в том, что во всех остальных контроллерах те же Item и Booker мы получаем через Dto(то есть немного изменяем, может убираем какую информацию от посторонних глаз). А так получается что получив букинг и открыв его, мы сможем увидеть обычные айтем и букер. Так что их я решил так же в виде Dto отдавать.

2022-09-05 19:55 UTC, PorotikovSergey commented
Я, вроде всё исправил, только 2 момента оставил.
1)переменную itemOwnerId я не стал переименовывать в ownerId. С одной стороны вроде и вправду излишне, а с другой есть ощущение, что "айди владельца" не совсем точно определяет владелец чего- может это человек на кого оформлено бронирование, или человек оставивший на него запрос... А так сразу становится понятно, что это владелец арендованной вещи.
2)название метода getReferenceById() - это ж из стандартных запросов к JpaRepository. Это не я придумал
А, ну и в букинге, который возвращается на запрос внутренние поля(те что Item и Booker) я сделал что б они были не своими обычными классами, а Dto. Логика в том, что во всех остальных контроллерах те же Item и Booker мы получаем через Dto(то есть немного изменяем, может убираем какую информацию от посторонних глаз). А так получается что получив букинг и открыв его, мы сможем увидеть обычные айтем и букер. Так что их я решил так же в виде Dto отдавать.

2022-09-07 12:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private UserDto booker;
в классах, которые представляют сущность из дб, поля тоже стоит делать типами с того же слоя приложения

иначе получается смешение и слоя дто, и слоя дао

2022-09-07 12:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingDto.java
> +    private long itemOwnerId;
хорошо

2022-09-07 12:15 UTC, makholin requested changes
нужно вернуть старые типы полей. чтобы в дао модели не было дто полей

по getReference давай обсудим в слаке

2022-09-08 10:08 UTC, makholin approved these changes
Работа принята

2022-09-09 16:28 UTC, merged